[package]
name = "cidr-tool"
version = "0.1.0"
edition = "2021"
authors = ["Tommaso Cammelli <tomm.camm@protonmail.ch>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "2.5.0"